/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mephi2023.mortalkombatbversion;

import mephi2023.mortalkombatbversion.heroes.Human;
import mephi2023.mortalkombatbversion.heroes.Player;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;


/** 
 * Класс JFrames для визуализации игры.
 * @autor Мария
*/
public class JFrames extends javax.swing.JFrame {
    
    Game game = new Game();
    Human human = null;
    Player enemy = null;
    String nameButton = "";

    
    /** 
    * Конструктор.
    */
    public JFrames() {
        initComponents();
        try {
            game.ReadFromExcel();
        } catch (IOException ex) {
            Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
        }
        game.WriteToTable(recordsTable);
        
        itemsButtonGroup.add(smallPotionRadioButton);
        itemsButtonGroup.add(bigPotionRadioButton);
        itemsButtonGroup.add(resurrectionCrossRadioButton);
        
        playerImageLabel.setIcon(new ImageIcon(".\\resources\\Kitana.png"));
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fightFrame = new javax.swing.JFrame();
        fightPanel = new javax.swing.JPanel();
        playerImageLabel = new javax.swing.JLabel();
        attackButton = new javax.swing.JButton();
        defendButton = new javax.swing.JButton();
        playerLifeProgressBar = new javax.swing.JProgressBar();
        enemyImageLabel = new javax.swing.JLabel();
        enemyLifeProgressBar = new javax.swing.JProgressBar();
        enemyNameLabel = new javax.swing.JLabel();
        damageTextLabel = new javax.swing.JLabel();
        damageText2Label = new javax.swing.JLabel();
        damageValue2Label = new javax.swing.JLabel();
        damageValueLabel = new javax.swing.JLabel();
        playerLevelLabel = new javax.swing.JLabel();
        fightTextLabel = new javax.swing.JLabel();
        playerLifeRemainderLabel = new javax.swing.JLabel();
        enemyLifeRemainderLabel = new javax.swing.JLabel();
        experienceTextLabel = new javax.swing.JLabel();
        pointsTextLabel = new javax.swing.JLabel();
        experienceValueLabel = new javax.swing.JLabel();
        pointsValueLabel = new javax.swing.JLabel();
        enemyLevelLabel = new javax.swing.JLabel();
        whosTurnLabel = new javax.swing.JLabel();
        anotherTurnLabel = new javax.swing.JLabel();
        playerNameLabel = new javax.swing.JLabel();
        additionalInformationLabel = new javax.swing.JLabel();
        bagOfItemsButton = new javax.swing.JButton();
        tempLocationLabel = new javax.swing.JLabel();
        countEnemiesLabel = new javax.swing.JLabel();
        tempEnemiesLabel = new javax.swing.JLabel();
        countLocationLabel = new javax.swing.JLabel();
        tempRooomLabel = new javax.swing.JLabel();
        tempRooomLabel1 = new javax.swing.JLabel();
        transitionDialog = new javax.swing.JDialog();
        transitionPanel = new javax.swing.JPanel();
        transitionInformationLabel = new javax.swing.JLabel();
        transitionButton = new javax.swing.JButton();
        askHealthOrDamageLabel = new javax.swing.JLabel();
        healthRadioButton = new javax.swing.JRadioButton();
        damageRadioButton = new javax.swing.JRadioButton();
        winGameIn10Dialog = new javax.swing.JDialog();
        winGameIn10Panel = new javax.swing.JPanel();
        winInformation2Label = new javax.swing.JLabel();
        namePlayerTextField = new javax.swing.JTextField();
        instructionForName1Label = new javax.swing.JLabel();
        instructionForName2Label = new javax.swing.JLabel();
        finishGame2Button = new javax.swing.JButton();
        recordsTableDialog = new javax.swing.JDialog();
        recordsTablePanel = new javax.swing.JPanel();
        recordsTableLabel = new javax.swing.JLabel();
        recordsTableScrollPane = new javax.swing.JScrollPane();
        recordsTable = new javax.swing.JTable();
        closeRecordsTableButton = new javax.swing.JButton();
        winGameNot10Dialog = new javax.swing.JDialog();
        winGameNot10Panel = new javax.swing.JPanel();
        winInformationLabel = new javax.swing.JLabel();
        winGameNot10Label = new javax.swing.JLabel();
        finishGameButton = new javax.swing.JButton();
        bagOfItemsDialog = new javax.swing.JDialog();
        bagOfItemsPanel = new javax.swing.JPanel();
        bagOfItemsLabel = new javax.swing.JLabel();
        smallPotionRadioButton = new javax.swing.JRadioButton();
        bigPotionRadioButton = new javax.swing.JRadioButton();
        resurrectionCrossRadioButton = new javax.swing.JRadioButton();
        useItemButton = new javax.swing.JButton();
        itemsButtonGroup = new javax.swing.ButtonGroup();
        impossibleUseThingDialog = new javax.swing.JDialog();
        impossibleUseThingDialogPanel = new javax.swing.JPanel();
        iformationPart1Label = new javax.swing.JLabel();
        informationPart2Label = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        chooseCountLocationDialog = new javax.swing.JDialog();
        chooseCountLocationPanel = new javax.swing.JPanel();
        instructionChooseCountLabel = new javax.swing.JLabel();
        countLocationTextField = new javax.swing.JTextField();
        okCountLocationButton = new javax.swing.JButton();
        exceptionLabel = new javax.swing.JLabel();
        chooseHealthOrDamageDialog = new javax.swing.JDialog();
        chooseHealthOrDamagePanel = new javax.swing.JPanel();
        askHealthOrDamageLabel2 = new javax.swing.JLabel();
        healthRadioButton2 = new javax.swing.JRadioButton();
        damageRadioButton2 = new javax.swing.JRadioButton();
        okHealthOrDamageButton2 = new javax.swing.JButton();
        hdButtonGroup = new javax.swing.ButtonGroup();
        startPanel = new javax.swing.JPanel();
        gameNameLabel = new javax.swing.JLabel();
        startNewGameButton = new javax.swing.JButton();
        seeResultsTableButton = new javax.swing.JButton();

        fightPanel.setBackground(new java.awt.Color(255, 255, 255));

        attackButton.setBackground(new java.awt.Color(255, 0, 0));
        attackButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        attackButton.setText("Атаковать");
        attackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackButtonActionPerformed(evt);
            }
        });

        defendButton.setBackground(new java.awt.Color(255, 204, 0));
        defendButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        defendButton.setText("Защититься");
        defendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defendButtonActionPerformed(evt);
            }
        });

        playerLifeProgressBar.setBackground(new java.awt.Color(204, 204, 204));
        playerLifeProgressBar.setForeground(new java.awt.Color(51, 255, 51));
        playerLifeProgressBar.setMaximum(80);
        playerLifeProgressBar.setMinimum(-1);

        enemyLifeProgressBar.setBackground(new java.awt.Color(204, 204, 204));
        enemyLifeProgressBar.setForeground(new java.awt.Color(0, 255, 0));
        enemyLifeProgressBar.setMinimum(-1);

        enemyNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        enemyNameLabel.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N

        damageTextLabel.setBackground(new java.awt.Color(255, 255, 255));
        damageTextLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        damageTextLabel.setText("Damage");

        damageText2Label.setBackground(new java.awt.Color(255, 255, 255));
        damageText2Label.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        damageText2Label.setText("Damage");

        damageValue2Label.setBackground(new java.awt.Color(255, 255, 255));
        damageValue2Label.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        damageValue2Label.setForeground(new java.awt.Color(255, 0, 0));
        damageValue2Label.setText("16");

        damageValueLabel.setBackground(new java.awt.Color(255, 255, 255));
        damageValueLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        damageValueLabel.setForeground(new java.awt.Color(255, 0, 0));
        damageValueLabel.setText("16");

        playerLevelLabel.setBackground(new java.awt.Color(255, 255, 255));
        playerLevelLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        playerLevelLabel.setText("0 уровень");

        fightTextLabel.setBackground(new java.awt.Color(255, 255, 255));
        fightTextLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        fightTextLabel.setForeground(new java.awt.Color(0, 0, 153));
        fightTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fightTextLabel.setText("FIGHT");
        fightTextLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        playerLifeRemainderLabel.setBackground(new java.awt.Color(255, 255, 255));
        playerLifeRemainderLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        playerLifeRemainderLabel.setForeground(new java.awt.Color(102, 102, 102));
        playerLifeRemainderLabel.setText("80/80");

        enemyLifeRemainderLabel.setBackground(new java.awt.Color(255, 255, 255));
        enemyLifeRemainderLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        enemyLifeRemainderLabel.setForeground(new java.awt.Color(102, 102, 102));
        enemyLifeRemainderLabel.setText("80/80");

        experienceTextLabel.setBackground(new java.awt.Color(255, 255, 255));
        experienceTextLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        experienceTextLabel.setForeground(new java.awt.Color(128, 92, 31));
        experienceTextLabel.setText("experience");

        pointsTextLabel.setBackground(new java.awt.Color(255, 255, 255));
        pointsTextLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        pointsTextLabel.setForeground(new java.awt.Color(128, 92, 31));
        pointsTextLabel.setText("points");

        experienceValueLabel.setBackground(new java.awt.Color(255, 255, 255));
        experienceValueLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        experienceValueLabel.setForeground(new java.awt.Color(113, 90, 16));
        experienceValueLabel.setText("0/40");

        pointsValueLabel.setBackground(new java.awt.Color(255, 255, 255));
        pointsValueLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        pointsValueLabel.setForeground(new java.awt.Color(113, 90, 16));
        pointsValueLabel.setText("00");

        enemyLevelLabel.setBackground(new java.awt.Color(255, 255, 255));
        enemyLevelLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        enemyLevelLabel.setText("1 уровень");

        whosTurnLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        whosTurnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        anotherTurnLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        anotherTurnLabel.setForeground(new java.awt.Color(204, 0, 0));
        anotherTurnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        playerNameLabel.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        playerNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerNameLabel.setText("Kitana ");

        additionalInformationLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        additionalInformationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        bagOfItemsButton.setBackground(new java.awt.Color(174, 183, 106));
        bagOfItemsButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        bagOfItemsButton.setText("Предметы");
        bagOfItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagOfItemsButtonActionPerformed(evt);
            }
        });

        tempLocationLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tempLocationLabel.setText("0");

        countEnemiesLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        countEnemiesLabel.setText("0");

        tempEnemiesLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tempEnemiesLabel.setText("0");

        countLocationLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        countLocationLabel.setText("0");

        tempRooomLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tempRooomLabel.setText("Текущая комната:");

        tempRooomLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tempRooomLabel1.setText("Всего комнат:");

        javax.swing.GroupLayout fightPanelLayout = new javax.swing.GroupLayout(fightPanel);
        fightPanel.setLayout(fightPanelLayout);
        fightPanelLayout.setHorizontalGroup(
            fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fightPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enemyLevelLabel)
                    .addComponent(enemyLifeRemainderLabel)
                    .addComponent(tempRooomLabel)
                    .addComponent(tempLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fightPanelLayout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fightTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(experienceTextLabel))
                        .addContainerGap())
                    .addGroup(fightPanelLayout.createSequentialGroup()
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fightPanelLayout.createSequentialGroup()
                                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bagOfItemsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(fightPanelLayout.createSequentialGroup()
                                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(fightPanelLayout.createSequentialGroup()
                                                .addComponent(damageTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(damageValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(fightPanelLayout.createSequentialGroup()
                                                .addComponent(enemyLifeProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(fightPanelLayout.createSequentialGroup()
                                                        .addGap(92, 92, 92)
                                                        .addComponent(pointsTextLabel))
                                                    .addGroup(fightPanelLayout.createSequentialGroup()
                                                        .addGap(111, 111, 111)
                                                        .addComponent(pointsValueLabel)
                                                        .addGap(108, 108, 108)
                                                        .addComponent(experienceValueLabel)))))
                                        .addGap(21, 21, 21)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fightPanelLayout.createSequentialGroup()
                                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fightPanelLayout.createSequentialGroup()
                                        .addComponent(enemyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(enemyImageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(fightPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(countLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tempRooomLabel1))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(whosTurnLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(anotherTurnLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(additionalInformationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(fightPanelLayout.createSequentialGroup()
                                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fightPanelLayout.createSequentialGroup()
                                        .addComponent(damageText2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(damageValue2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(fightPanelLayout.createSequentialGroup()
                                        .addComponent(playerLifeProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(playerLifeRemainderLabel)))
                                .addGap(45, 45, 45))
                            .addGroup(fightPanelLayout.createSequentialGroup()
                                .addComponent(playerLevelLabel)
                                .addContainerGap())
                            .addGroup(fightPanelLayout.createSequentialGroup()
                                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(fightPanelLayout.createSequentialGroup()
                                        .addComponent(attackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(defendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(playerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tempEnemiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(playerImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19)
                                .addComponent(countEnemiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        fightPanelLayout.setVerticalGroup(
            fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fightPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fightPanelLayout.createSequentialGroup()
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tempRooomLabel)
                            .addComponent(tempRooomLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fightTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tempLocationLabel)
                                .addComponent(countLocationLabel)))
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(experienceTextLabel)
                            .addComponent(pointsTextLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(experienceValueLabel)
                            .addComponent(pointsValueLabel)))
                    .addGroup(fightPanelLayout.createSequentialGroup()
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tempEnemiesLabel)
                            .addComponent(countEnemiesLabel))
                        .addGap(62, 62, 62)
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(playerLifeProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(enemyLifeProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(fightPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(playerLifeRemainderLabel))
                            .addComponent(enemyLifeRemainderLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(damageText2Label)
                    .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(damageTextLabel)
                        .addComponent(damageValueLabel)
                        .addComponent(damageValue2Label)))
                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fightPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fightPanelLayout.createSequentialGroup()
                                .addComponent(anotherTurnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(whosTurnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(additionalInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(enemyImageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(fightPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(playerLevelLabel)
                            .addComponent(enemyLevelLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playerImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fightPanelLayout.createSequentialGroup()
                        .addComponent(playerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(fightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(defendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bagOfItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(enemyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fightFrameLayout = new javax.swing.GroupLayout(fightFrame.getContentPane());
        fightFrame.getContentPane().setLayout(fightFrameLayout);
        fightFrameLayout.setHorizontalGroup(
            fightFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fightFrameLayout.createSequentialGroup()
                .addComponent(fightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        fightFrameLayout.setVerticalGroup(
            fightFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fightPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        transitionPanel.setBackground(new java.awt.Color(179, 226, 217));

        transitionInformationLabel.setBackground(new java.awt.Color(204, 204, 204));
        transitionInformationLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 42)); // NOI18N
        transitionInformationLabel.setForeground(new java.awt.Color(204, 0, 0));
        transitionInformationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transitionInformationLabel.setText("jLabel18");
        transitionInformationLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        transitionButton.setBackground(new java.awt.Color(114, 218, 142));
        transitionButton.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        transitionButton.setText("Дальше");
        transitionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transitionButtonActionPerformed(evt);
            }
        });

        askHealthOrDamageLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        askHealthOrDamageLabel.setText("Что хотите увеличить?");

        hdButtonGroup.add(healthRadioButton);
        healthRadioButton.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        healthRadioButton.setText("Здоровье");
        healthRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthRadioButtonActionPerformed(evt);
            }
        });

        hdButtonGroup.add(damageRadioButton);
        damageRadioButton.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        damageRadioButton.setText("Урон");

        javax.swing.GroupLayout transitionPanelLayout = new javax.swing.GroupLayout(transitionPanel);
        transitionPanel.setLayout(transitionPanelLayout);
        transitionPanelLayout.setHorizontalGroup(
            transitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transitionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transitionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
            .addGroup(transitionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(askHealthOrDamageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(transitionPanelLayout.createSequentialGroup()
                .addGroup(transitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transitionPanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(transitionInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transitionPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(healthRadioButton))
                    .addGroup(transitionPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(damageRadioButton)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        transitionPanelLayout.setVerticalGroup(
            transitionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transitionPanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(transitionInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(askHealthOrDamageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(healthRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(damageRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(transitionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout transitionDialogLayout = new javax.swing.GroupLayout(transitionDialog.getContentPane());
        transitionDialog.getContentPane().setLayout(transitionDialogLayout);
        transitionDialogLayout.setHorizontalGroup(
            transitionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transitionDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transitionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        transitionDialogLayout.setVerticalGroup(
            transitionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transitionDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transitionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        winGameIn10Panel.setBackground(new java.awt.Color(255, 204, 255));

        winInformation2Label.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        winInformation2Label.setForeground(new java.awt.Color(255, 0, 0));
        winInformation2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winInformation2Label.setText("Победа на вашей стороне");

        namePlayerTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        namePlayerTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        namePlayerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namePlayerTextFieldActionPerformed(evt);
            }
        });

        instructionForName1Label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        instructionForName1Label.setForeground(new java.awt.Color(102, 102, 102));
        instructionForName1Label.setText("Введите имя своего персонажа для добавления");

        instructionForName2Label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        instructionForName2Label.setForeground(new java.awt.Color(102, 102, 102));
        instructionForName2Label.setText("результата в таблицу рекордов");

        finishGame2Button.setBackground(new java.awt.Color(153, 153, 255));
        finishGame2Button.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        finishGame2Button.setForeground(new java.awt.Color(51, 51, 51));
        finishGame2Button.setText("Закончить игру");
        finishGame2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishGame2ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout winGameIn10PanelLayout = new javax.swing.GroupLayout(winGameIn10Panel);
        winGameIn10Panel.setLayout(winGameIn10PanelLayout);
        winGameIn10PanelLayout.setHorizontalGroup(
            winGameIn10PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winGameIn10PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(finishGame2Button)
                .addGap(14, 14, 14))
            .addGroup(winGameIn10PanelLayout.createSequentialGroup()
                .addGroup(winGameIn10PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(winGameIn10PanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(instructionForName2Label))
                    .addGroup(winGameIn10PanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(winInformation2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(winGameIn10PanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(winGameIn10PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namePlayerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instructionForName1Label))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        winGameIn10PanelLayout.setVerticalGroup(
            winGameIn10PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winGameIn10PanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(winInformation2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instructionForName1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionForName2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(namePlayerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finishGame2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout winGameIn10DialogLayout = new javax.swing.GroupLayout(winGameIn10Dialog.getContentPane());
        winGameIn10Dialog.getContentPane().setLayout(winGameIn10DialogLayout);
        winGameIn10DialogLayout.setHorizontalGroup(
            winGameIn10DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winGameIn10DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(winGameIn10Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        winGameIn10DialogLayout.setVerticalGroup(
            winGameIn10DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winGameIn10DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(winGameIn10Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        recordsTablePanel.setBackground(new java.awt.Color(204, 204, 255));

        recordsTableLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        recordsTableLabel.setForeground(new java.awt.Color(51, 51, 51));
        recordsTableLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recordsTableLabel.setText("Таблица рекордов");

        recordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Имя", "Количество баллов"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        recordsTableScrollPane.setViewportView(recordsTable);

        closeRecordsTableButton.setBackground(new java.awt.Color(255, 255, 153));
        closeRecordsTableButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        closeRecordsTableButton.setForeground(new java.awt.Color(51, 51, 51));
        closeRecordsTableButton.setText("Закрыть");
        closeRecordsTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeRecordsTableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recordsTablePanelLayout = new javax.swing.GroupLayout(recordsTablePanel);
        recordsTablePanel.setLayout(recordsTablePanelLayout);
        recordsTablePanelLayout.setHorizontalGroup(
            recordsTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordsTablePanelLayout.createSequentialGroup()
                .addGroup(recordsTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closeRecordsTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(recordsTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(recordsTablePanelLayout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(recordsTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(recordsTablePanelLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(recordsTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        recordsTablePanelLayout.setVerticalGroup(
            recordsTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordsTablePanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(recordsTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recordsTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeRecordsTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout recordsTableDialogLayout = new javax.swing.GroupLayout(recordsTableDialog.getContentPane());
        recordsTableDialog.getContentPane().setLayout(recordsTableDialogLayout);
        recordsTableDialogLayout.setHorizontalGroup(
            recordsTableDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recordsTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        recordsTableDialogLayout.setVerticalGroup(
            recordsTableDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recordsTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        winGameNot10Panel.setBackground(new java.awt.Color(255, 204, 255));

        winInformationLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        winInformationLabel.setForeground(new java.awt.Color(255, 0, 0));
        winInformationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winInformationLabel.setText("Победа на вашей стороне");

        winGameNot10Label.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        winGameNot10Label.setForeground(new java.awt.Color(102, 102, 102));
        winGameNot10Label.setText("К сожалению, Ваш результат не попал в топ 10");

        finishGameButton.setBackground(new java.awt.Color(153, 153, 255));
        finishGameButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        finishGameButton.setForeground(new java.awt.Color(51, 51, 51));
        finishGameButton.setText("Закончить игру");
        finishGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout winGameNot10PanelLayout = new javax.swing.GroupLayout(winGameNot10Panel);
        winGameNot10Panel.setLayout(winGameNot10PanelLayout);
        winGameNot10PanelLayout.setHorizontalGroup(
            winGameNot10PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winGameNot10PanelLayout.createSequentialGroup()
                .addGroup(winGameNot10PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(winGameNot10PanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(winInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(winGameNot10PanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(winGameNot10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(winGameNot10PanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(finishGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        winGameNot10PanelLayout.setVerticalGroup(
            winGameNot10PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winGameNot10PanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(winInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(winGameNot10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(finishGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout winGameNot10DialogLayout = new javax.swing.GroupLayout(winGameNot10Dialog.getContentPane());
        winGameNot10Dialog.getContentPane().setLayout(winGameNot10DialogLayout);
        winGameNot10DialogLayout.setHorizontalGroup(
            winGameNot10DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(winGameNot10Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        winGameNot10DialogLayout.setVerticalGroup(
            winGameNot10DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(winGameNot10Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bagOfItemsPanel.setBackground(new java.awt.Color(190, 182, 135));

        bagOfItemsLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        bagOfItemsLabel.setForeground(new java.awt.Color(51, 51, 51));
        bagOfItemsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bagOfItemsLabel.setText("Мешок предметов");

        smallPotionRadioButton.setBackground(new java.awt.Color(190, 182, 135));
        itemsButtonGroup.add(smallPotionRadioButton);
        smallPotionRadioButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        smallPotionRadioButton.setText("Малое зелье лечение, 0 шт");
        smallPotionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallPotionRadioButtonActionPerformed(evt);
            }
        });

        bigPotionRadioButton.setBackground(new java.awt.Color(190, 182, 135));
        itemsButtonGroup.add(bigPotionRadioButton);
        bigPotionRadioButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        bigPotionRadioButton.setText("Большое зелье лечение, 0 шт");
        bigPotionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigPotionRadioButtonActionPerformed(evt);
            }
        });

        resurrectionCrossRadioButton.setBackground(new java.awt.Color(190, 182, 135));
        itemsButtonGroup.add(resurrectionCrossRadioButton);
        resurrectionCrossRadioButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        resurrectionCrossRadioButton.setText("Крест возрождения, 0 шт");

        useItemButton.setBackground(new java.awt.Color(239, 237, 14));
        useItemButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        useItemButton.setText("Использовать");
        useItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bagOfItemsPanelLayout = new javax.swing.GroupLayout(bagOfItemsPanel);
        bagOfItemsPanel.setLayout(bagOfItemsPanelLayout);
        bagOfItemsPanelLayout.setHorizontalGroup(
            bagOfItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bagOfItemsPanelLayout.createSequentialGroup()
                .addGroup(bagOfItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bagOfItemsPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(bagOfItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bigPotionRadioButton)
                            .addComponent(resurrectionCrossRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(smallPotionRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bagOfItemsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bagOfItemsPanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(useItemButton)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        bagOfItemsPanelLayout.setVerticalGroup(
            bagOfItemsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bagOfItemsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bagOfItemsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(smallPotionRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bigPotionRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resurrectionCrossRadioButton)
                .addGap(50, 50, 50)
                .addComponent(useItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bagOfItemsDialogLayout = new javax.swing.GroupLayout(bagOfItemsDialog.getContentPane());
        bagOfItemsDialog.getContentPane().setLayout(bagOfItemsDialogLayout);
        bagOfItemsDialogLayout.setHorizontalGroup(
            bagOfItemsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bagOfItemsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bagOfItemsDialogLayout.setVerticalGroup(
            bagOfItemsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bagOfItemsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        impossibleUseThingDialogPanel.setBackground(new java.awt.Color(243, 120, 120));

        iformationPart1Label.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        iformationPart1Label.setForeground(new java.awt.Color(51, 51, 51));
        iformationPart1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iformationPart1Label.setText("Вы не можете использовать ");

        informationPart2Label.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        informationPart2Label.setForeground(new java.awt.Color(51, 51, 51));
        informationPart2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        informationPart2Label.setText("этот предмет");

        okButton.setBackground(new java.awt.Color(204, 204, 204));
        okButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        okButton.setForeground(new java.awt.Color(51, 51, 51));
        okButton.setText("ОК");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout impossibleUseThingDialogPanelLayout = new javax.swing.GroupLayout(impossibleUseThingDialogPanel);
        impossibleUseThingDialogPanel.setLayout(impossibleUseThingDialogPanelLayout);
        impossibleUseThingDialogPanelLayout.setHorizontalGroup(
            impossibleUseThingDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(impossibleUseThingDialogPanelLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(impossibleUseThingDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, impossibleUseThingDialogPanelLayout.createSequentialGroup()
                        .addComponent(iformationPart1Label)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, impossibleUseThingDialogPanelLayout.createSequentialGroup()
                        .addComponent(informationPart2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))))
            .addGroup(impossibleUseThingDialogPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        impossibleUseThingDialogPanelLayout.setVerticalGroup(
            impossibleUseThingDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(impossibleUseThingDialogPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(iformationPart1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informationPart2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout impossibleUseThingDialogLayout = new javax.swing.GroupLayout(impossibleUseThingDialog.getContentPane());
        impossibleUseThingDialog.getContentPane().setLayout(impossibleUseThingDialogLayout);
        impossibleUseThingDialogLayout.setHorizontalGroup(
            impossibleUseThingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(impossibleUseThingDialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        impossibleUseThingDialogLayout.setVerticalGroup(
            impossibleUseThingDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(impossibleUseThingDialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        instructionChooseCountLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        instructionChooseCountLabel.setText("Задайте количество локаций в игре (от 1 до 10 включительно):");

        okCountLocationButton.setText("OK");
        okCountLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okCountLocationButtonActionPerformed(evt);
            }
        });

        exceptionLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        javax.swing.GroupLayout chooseCountLocationPanelLayout = new javax.swing.GroupLayout(chooseCountLocationPanel);
        chooseCountLocationPanel.setLayout(chooseCountLocationPanelLayout);
        chooseCountLocationPanelLayout.setHorizontalGroup(
            chooseCountLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseCountLocationPanelLayout.createSequentialGroup()
                .addGroup(chooseCountLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chooseCountLocationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(instructionChooseCountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(chooseCountLocationPanelLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(chooseCountLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(countLocationTextField)
                            .addComponent(okCountLocationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(exceptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        chooseCountLocationPanelLayout.setVerticalGroup(
            chooseCountLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseCountLocationPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(instructionChooseCountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(countLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okCountLocationButton)
                .addGap(18, 18, 18)
                .addComponent(exceptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout chooseCountLocationDialogLayout = new javax.swing.GroupLayout(chooseCountLocationDialog.getContentPane());
        chooseCountLocationDialog.getContentPane().setLayout(chooseCountLocationDialogLayout);
        chooseCountLocationDialogLayout.setHorizontalGroup(
            chooseCountLocationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chooseCountLocationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        chooseCountLocationDialogLayout.setVerticalGroup(
            chooseCountLocationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chooseCountLocationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        askHealthOrDamageLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        askHealthOrDamageLabel2.setText("Что хотите увеличить?");

        hdButtonGroup.add(healthRadioButton2);
        healthRadioButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        healthRadioButton2.setText("Здоровье");
        healthRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healthRadioButton2ActionPerformed(evt);
            }
        });

        hdButtonGroup.add(damageRadioButton2);
        damageRadioButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        damageRadioButton2.setText("Урон");

        okHealthOrDamageButton2.setText("OK");
        okHealthOrDamageButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okHealthOrDamageButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chooseHealthOrDamagePanelLayout = new javax.swing.GroupLayout(chooseHealthOrDamagePanel);
        chooseHealthOrDamagePanel.setLayout(chooseHealthOrDamagePanelLayout);
        chooseHealthOrDamagePanelLayout.setHorizontalGroup(
            chooseHealthOrDamagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseHealthOrDamagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chooseHealthOrDamagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(askHealthOrDamageLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(chooseHealthOrDamagePanelLayout.createSequentialGroup()
                        .addGroup(chooseHealthOrDamagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(healthRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(damageRadioButton2)
                            .addComponent(okHealthOrDamageButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        chooseHealthOrDamagePanelLayout.setVerticalGroup(
            chooseHealthOrDamagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseHealthOrDamagePanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(askHealthOrDamageLabel2)
                .addGap(18, 18, 18)
                .addComponent(healthRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(damageRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(okHealthOrDamageButton2)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout chooseHealthOrDamageDialogLayout = new javax.swing.GroupLayout(chooseHealthOrDamageDialog.getContentPane());
        chooseHealthOrDamageDialog.getContentPane().setLayout(chooseHealthOrDamageDialogLayout);
        chooseHealthOrDamageDialogLayout.setHorizontalGroup(
            chooseHealthOrDamageDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chooseHealthOrDamagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        chooseHealthOrDamageDialogLayout.setVerticalGroup(
            chooseHealthOrDamageDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chooseHealthOrDamagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startPanel.setBackground(new java.awt.Color(255, 255, 255));

        gameNameLabel.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        gameNameLabel.setForeground(new java.awt.Color(204, 204, 0));
        gameNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameNameLabel.setText("Mortal Kombat");

        startNewGameButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        startNewGameButton.setText("Начать новую игру");
        startNewGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startNewGameButtonActionPerformed(evt);
            }
        });

        seeResultsTableButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        seeResultsTableButton.setText("Посмотреть таблицу \nрезультатов");
        seeResultsTableButton.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        seeResultsTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeResultsTableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(seeResultsTableButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(startNewGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(gameNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(gameNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seeResultsTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startNewGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /** 
    * Метод вызывается при нажатии "начать игру".
    */
    private void startNewGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startNewGameButtonActionPerformed
        chooseCountLocationDialog.setVisible(true);
        chooseCountLocationDialog.setBounds(100, 100, 580, 450);
        
    }//GEN-LAST:event_startNewGameButtonActionPerformed

    /** 
    * Метод вызывается при нажатии "атаковать".
    */
    private void attackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackButtonActionPerformed
        game.fight.Hit(human, enemy, 1, enemyLifeRemainderLabel, playerLifeRemainderLabel, transitionDialog, 
                transitionInformationLabel, game.action, playerLifeProgressBar, enemyLifeProgressBar, winGameIn10Dialog, 
                winGameNot10Dialog, fightFrame, game.getResults(), winInformation2Label, winInformationLabel, 
                whosTurnLabel, additionalInformationLabel, anotherTurnLabel, game.getItems(), resurrectionCrossRadioButton,
                chooseHealthOrDamageDialog, fightFrame, okHealthOrDamageButton2, askHealthOrDamageLabel, 
                             healthRadioButton,damageRadioButton,
                countLocationLabel, countEnemiesLabel, tempLocationLabel, tempEnemiesLabel);
        
    }//GEN-LAST:event_attackButtonActionPerformed

    /** 
    * Метод вызывается при нажатии "защититься".
    */
    private void defendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defendButtonActionPerformed
        game.fight.Hit(human, enemy, 0, enemyLifeRemainderLabel, playerLifeRemainderLabel, transitionDialog, 
                transitionInformationLabel, game.action, playerLifeProgressBar, enemyLifeProgressBar, winGameIn10Dialog, 
                winGameNot10Dialog, fightFrame, game.getResults(), winInformation2Label, winInformationLabel, 
                whosTurnLabel, additionalInformationLabel, anotherTurnLabel, game.getItems(), resurrectionCrossRadioButton,
                chooseHealthOrDamageDialog, fightFrame, okHealthOrDamageButton2, askHealthOrDamageLabel, 
                             healthRadioButton,damageRadioButton,
                countLocationLabel, countEnemiesLabel, tempLocationLabel, tempEnemiesLabel);
    }//GEN-LAST:event_defendButtonActionPerformed

    /** 
    * Метод вызывается при нажатии "далее".
    */
    private void transitionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transitionButtonActionPerformed
        
        if ((healthRadioButton.isSelected() || damageRadioButton.isSelected())
                & askHealthOrDamageLabel.isVisible()){
            transitionDialog.setVisible(true);
            if (healthRadioButton.isSelected()){
                human.NewHealthHuman(true);
                chooseHealthOrDamageDialog.dispose();
                healthRadioButton.setSelected(false);
            } else if (damageRadioButton.isSelected()){
                human.NewHealthHuman(false);
                chooseHealthOrDamageDialog.dispose();
                damageRadioButton.setSelected(false);
            }
            fightFrame.setVisible(true);
            enemy=game.fight.NewRound(human, enemyImageLabel, playerLifeProgressBar, enemyLifeProgressBar, 
                enemyNameLabel, damageValueLabel, enemyLifeRemainderLabel, game.action);

        
            game.change.NewRoundTexts(human, enemy, playerLifeProgressBar, enemyLifeProgressBar, 
                    pointsValueLabel, experienceValueLabel, playerLevelLabel, enemyLevelLabel, playerLifeRemainderLabel, enemyLifeRemainderLabel, damageValue2Label,
                    whosTurnLabel, anotherTurnLabel, game.fight.i, game.getItems(), smallPotionRadioButton, bigPotionRadioButton, resurrectionCrossRadioButton);

            transitionDialog.dispose();
        } else if (!askHealthOrDamageLabel.isVisible()){
            fightFrame.setVisible(true);
            enemy=game.fight.NewRound(human, enemyImageLabel, playerLifeProgressBar, enemyLifeProgressBar, 
                enemyNameLabel, damageValueLabel, enemyLifeRemainderLabel, game.action);

        
            game.change.NewRoundTexts(human, enemy, playerLifeProgressBar, enemyLifeProgressBar, 
                    pointsValueLabel, experienceValueLabel, playerLevelLabel, enemyLevelLabel, playerLifeRemainderLabel, enemyLifeRemainderLabel, damageValue2Label,
                    whosTurnLabel, anotherTurnLabel, game.fight.i, game.getItems(), smallPotionRadioButton, bigPotionRadioButton, resurrectionCrossRadioButton);

            transitionDialog.dispose();
        }
        
    }//GEN-LAST:event_transitionButtonActionPerformed

    private void namePlayerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namePlayerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namePlayerTextFieldActionPerformed

    /** 
    * Метод вызывается при нажатии "завершить игру" и игрок в топ-10.
    */
    private void finishGame2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishGame2ButtonActionPerformed
        try {
            game.EndGameTop(human, namePlayerTextField, recordsTable);
        } catch (IOException ex) {
            Logger.getLogger(JFrames.class.getName()).log(Level.SEVERE, null, ex);
        }
        winGameIn10Dialog.dispose();
        namePlayerTextField.setText("");
    }//GEN-LAST:event_finishGame2ButtonActionPerformed

    /** 
    * Метод вызывается при нажатии "закрыть таблицу".
    */
    private void closeRecordsTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeRecordsTableButtonActionPerformed
        recordsTableDialog.dispose();
    }//GEN-LAST:event_closeRecordsTableButtonActionPerformed

    /** 
    * Метод вызывается при нажатии "посмотреть результаты".
    */
    private void seeResultsTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeResultsTableButtonActionPerformed
        recordsTableDialog.setVisible(true);
        recordsTableDialog.setBounds(100, 100, 580, 450);
    }//GEN-LAST:event_seeResultsTableButtonActionPerformed

    /** 
    * Метод вызывается при нажатии "завершить игру" и игрок не в топ-10.
    */
    private void finishGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishGameButtonActionPerformed
        winGameNot10Dialog.dispose();
    }//GEN-LAST:event_finishGameButtonActionPerformed

    private void smallPotionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallPotionRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smallPotionRadioButtonActionPerformed

    private void bigPotionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigPotionRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bigPotionRadioButtonActionPerformed

    /** 
    * Метод вызывается при нажатии "использовать".
    */
    private void useItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useItemButtonActionPerformed
        if(smallPotionRadioButton.isSelected()){
            nameButton="smallPotionRadioButton";
        }
        if(bigPotionRadioButton.isSelected()){
            nameButton="bigPotionRadioButton";
        }
        if(resurrectionCrossRadioButton.isSelected()){
            nameButton="resurrectionCrossRadioButton";
        }
        game.action.UseItem(human, game.getItems(), nameButton, impossibleUseThingDialog, bagOfItemsDialog);
        game.action.HP(human, playerLifeProgressBar);
        playerLifeRemainderLabel.setText(human.getHealth() + "/" + human.getMaxHealth());
        game.change.BagText(game.getItems(), smallPotionRadioButton, bigPotionRadioButton, resurrectionCrossRadioButton);
    }//GEN-LAST:event_useItemButtonActionPerformed

    /** 
    * Метод вызывается при нажатии "предметы".
    */
    private void bagOfItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagOfItemsButtonActionPerformed
        bagOfItemsDialog.setVisible(true);
        bagOfItemsDialog.setBounds(300, 200, 430, 350);
    }//GEN-LAST:event_bagOfItemsButtonActionPerformed

    /** 
    * Метод вызывается при нажатии "ок", когда невозможно использовать вещь из запаса.
    */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        impossibleUseThingDialog.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /** 
    * Метод вызывается при нажатии "ок", когда введено количество локаций.
    */
    private void okCountLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okCountLocationButtonActionPerformed
        // TODO add your handling code here:        
        try{
            int n = Integer.parseInt(countLocationTextField.getText());
            System.out.println(n<1);
            if (n < 1 || n > 10){
                System.out.println(n);
                throw new Exception();
            }
            fightFrame.setVisible(rootPaneCheckingEnabled);
            fightFrame.setSize(1000,700);
            chooseCountLocationDialog.dispose();
            human = game.NewHuman(playerLifeProgressBar);
            human.setCountLocations(n);

            enemy = game.NewEnemy(enemyImageLabel, enemyNameLabel, damageValueLabel, enemyLifeRemainderLabel, enemyLifeProgressBar);

            game.change.NewRoundTexts(human, enemy, playerLifeProgressBar, enemyLifeProgressBar, 
                    pointsValueLabel, experienceValueLabel, playerLevelLabel, enemyLevelLabel, playerLifeRemainderLabel, enemyLifeRemainderLabel, damageValue2Label,
                    whosTurnLabel, anotherTurnLabel, game.fight.i, game.getItems(), smallPotionRadioButton, bigPotionRadioButton, resurrectionCrossRadioButton);

            countLocationLabel.setText(String.valueOf(((Human)human).getCountLocations()));
            tempLocationLabel.setText(String.valueOf(((Human)human).getTempLocations()));
            countEnemiesLabel.setText(String.valueOf(((Human)human).getCountEnemies()));
            tempEnemiesLabel.setText(String.valueOf(((Human)human).getTempEnemies()));
        } catch (Exception e){
            exceptionLabel.setText("Введено не корректное число, повторите попытку");
        }
    }//GEN-LAST:event_okCountLocationButtonActionPerformed

    private void healthRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_healthRadioButton2ActionPerformed

    private void okHealthOrDamageButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okHealthOrDamageButton2ActionPerformed
        // TODO add your handling code here
        if (healthRadioButton2.isSelected() || damageRadioButton2.isSelected()){
            transitionDialog.setVisible(true);
            if (healthRadioButton2.isSelected()){
            //CharacterAction.setChooseHealth(true);
            //NewHealthHuman(human, true);
            human.NewHealthHuman(true);
            chooseHealthOrDamageDialog.dispose();
        //fightFrame.setVisible(true);
        } else if (damageRadioButton2.isSelected()){
            //CharacterAction.setChooseHealth(false);
            //NewHealthHuman(human, false);
            human.NewHealthHuman(false);
            chooseHealthOrDamageDialog.dispose();
        //fightFrame.setVisible(true);
        }
        }
        
    }//GEN-LAST:event_okHealthOrDamageButton2ActionPerformed

    private void healthRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healthRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_healthRadioButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel additionalInformationLabel;
    private javax.swing.JLabel anotherTurnLabel;
    private javax.swing.JLabel askHealthOrDamageLabel;
    private javax.swing.JLabel askHealthOrDamageLabel2;
    private javax.swing.JButton attackButton;
    private javax.swing.JButton bagOfItemsButton;
    private javax.swing.JDialog bagOfItemsDialog;
    private javax.swing.JLabel bagOfItemsLabel;
    private javax.swing.JPanel bagOfItemsPanel;
    private javax.swing.JRadioButton bigPotionRadioButton;
    private javax.swing.JDialog chooseCountLocationDialog;
    private javax.swing.JPanel chooseCountLocationPanel;
    private javax.swing.JDialog chooseHealthOrDamageDialog;
    private javax.swing.JPanel chooseHealthOrDamagePanel;
    private javax.swing.JButton closeRecordsTableButton;
    private javax.swing.JLabel countEnemiesLabel;
    private javax.swing.JLabel countLocationLabel;
    private javax.swing.JTextField countLocationTextField;
    private javax.swing.JRadioButton damageRadioButton;
    private javax.swing.JRadioButton damageRadioButton2;
    private javax.swing.JLabel damageText2Label;
    private javax.swing.JLabel damageTextLabel;
    private javax.swing.JLabel damageValue2Label;
    private javax.swing.JLabel damageValueLabel;
    private javax.swing.JButton defendButton;
    private javax.swing.JLabel enemyImageLabel;
    private javax.swing.JLabel enemyLevelLabel;
    private javax.swing.JProgressBar enemyLifeProgressBar;
    private javax.swing.JLabel enemyLifeRemainderLabel;
    private javax.swing.JLabel enemyNameLabel;
    private javax.swing.JLabel exceptionLabel;
    private javax.swing.JLabel experienceTextLabel;
    private javax.swing.JLabel experienceValueLabel;
    private javax.swing.JFrame fightFrame;
    private javax.swing.JPanel fightPanel;
    private javax.swing.JLabel fightTextLabel;
    private javax.swing.JButton finishGame2Button;
    private javax.swing.JButton finishGameButton;
    private javax.swing.JLabel gameNameLabel;
    private javax.swing.ButtonGroup hdButtonGroup;
    private javax.swing.JRadioButton healthRadioButton;
    private javax.swing.JRadioButton healthRadioButton2;
    private javax.swing.JLabel iformationPart1Label;
    private javax.swing.JDialog impossibleUseThingDialog;
    private javax.swing.JPanel impossibleUseThingDialogPanel;
    private javax.swing.JLabel informationPart2Label;
    private javax.swing.JLabel instructionChooseCountLabel;
    private javax.swing.JLabel instructionForName1Label;
    private javax.swing.JLabel instructionForName2Label;
    private javax.swing.ButtonGroup itemsButtonGroup;
    private javax.swing.JTextField namePlayerTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JButton okCountLocationButton;
    private javax.swing.JButton okHealthOrDamageButton2;
    private javax.swing.JLabel playerImageLabel;
    private javax.swing.JLabel playerLevelLabel;
    private javax.swing.JProgressBar playerLifeProgressBar;
    private javax.swing.JLabel playerLifeRemainderLabel;
    private javax.swing.JLabel playerNameLabel;
    private javax.swing.JLabel pointsTextLabel;
    private javax.swing.JLabel pointsValueLabel;
    private javax.swing.JTable recordsTable;
    private javax.swing.JDialog recordsTableDialog;
    private javax.swing.JLabel recordsTableLabel;
    private javax.swing.JPanel recordsTablePanel;
    private javax.swing.JScrollPane recordsTableScrollPane;
    private javax.swing.JRadioButton resurrectionCrossRadioButton;
    private javax.swing.JButton seeResultsTableButton;
    private javax.swing.JRadioButton smallPotionRadioButton;
    private javax.swing.JButton startNewGameButton;
    private javax.swing.JPanel startPanel;
    private javax.swing.JLabel tempEnemiesLabel;
    private javax.swing.JLabel tempLocationLabel;
    private javax.swing.JLabel tempRooomLabel;
    private javax.swing.JLabel tempRooomLabel1;
    private javax.swing.JButton transitionButton;
    private javax.swing.JDialog transitionDialog;
    private javax.swing.JLabel transitionInformationLabel;
    private javax.swing.JPanel transitionPanel;
    private javax.swing.JButton useItemButton;
    private javax.swing.JLabel whosTurnLabel;
    private javax.swing.JDialog winGameIn10Dialog;
    private javax.swing.JPanel winGameIn10Panel;
    private javax.swing.JDialog winGameNot10Dialog;
    private javax.swing.JLabel winGameNot10Label;
    private javax.swing.JPanel winGameNot10Panel;
    private javax.swing.JLabel winInformation2Label;
    private javax.swing.JLabel winInformationLabel;
    // End of variables declaration//GEN-END:variables
}
